### ISSUE TITLE
use fuse rcore-fs check fail! 使用 fuse rcore-fs生成文件后 魔数检查失败

### ISSUE THREAD

**Issue by zzhgithub** [rcore-os/rcore-fs#21]
# dependency
rcore-fs = { git = "https://github.com/rcore-os/rcore-fs", rev = "517af47" }
rcore-fs-devfs = { git = "https://github.com/rcore-os/rcore-fs", rev = "517af47" }
rcore-fs-sfs = { git = "https://github.com/rcore-os/rcore-fs", rev = "517af47" }
rcore-fs-mountfs = { git = "https://github.com/rcore-os/rcore-fs", rev = "517af47" }

and in makefile:
rcore_fs_fuse_revision := 7f5eeac

full code [https://github.com/zzhgithub/juner_os/tree/file](https://github.com/zzhgithub/juner_os/tree/file)
and link [issues](https://github.com/zzhgithub/juner_os/issues/4)

I use rcore-fs-fuse and qemu-img convert to qcow2.and use ahci device. but got a error:
```
[Info] :# panicked at 'failed to open SFS: WrongFs', kernel/src/fs/mod.rs:33:50
```

How to fix it?
Thank you. Or can you advice me a  gdb tool for rust on mac?

**Comment by jiegec** [comment]
you need to ensure that rcore-fs-fuse to have to same version as library.

**Comment by zzhgithub** [comment]
> you need to ensure that rcore-fs-fuse has the same version as library.

Oh Curiously , I use rcore-fs with version 517af47 but got the same problem.

**Comment by zzhgithub** [comment]
And now Just find following:
```
[Info] :# [DEBUG] magic is 2457639
[Info] :# [DEBUG] Test is 797818411
```

**Comment by zzhgithub** [comment]
Ok all My fulat .
I didn't  right impl the Provider!!! 哈哈
thank for all of your ansers.
